version: 0.2
env:
  variables:
    BUILD_CONFIGURATION: "production"
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
      - npm install --save-dev karma-junit-reporter
      - wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt update && apt install -y libappindicator1 fonts-liberation ./google-chrome-stable_current_amd64.deb
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=${BUILD_CONFIGURATION}
  post_build:
    commands:
      - echo Testing started on `date`
      - ng test --reporters junit --watch=false
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
reports:
  junit-reports:
    files:
      - "reports/junit/*.xml"
    file-format: "JUNITXML"
  coverage-reports:
    files:
      - "reports/coverage/*.xml"
    file-format: "COBERTURAXML"
